##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/paybpymi/atellastudios.paybuymart.com/wp-content/themes/atellastudios/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R inc $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R languages $DEPLOYPATH
    - /bin/cp -R template-parts $DEPLOYPATH
    - /bin/cp -R videos $DEPLOYPATH

    - /bin/cp .eslintrc $DEPLOYPATH
    - /bin/cp .stylelintrc.json $DEPLOYPATH
    - /bin/cp 404.php $DEPLOYPATH
    - /bin/cp about-page.php $DEPLOYPATH
    - /bin/cp comments.php $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp front-page.php $DEPLOYPATH
    - /bin/cp functions.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp page.php $DEPLOYPATH
    - /bin/cp phpcs.xml.dist $DEPLOYPATH
    - /bin/cp readme.txt $DEPLOYPATH
    - /bin/cp screenshot.png $DEPLOYPATH
    - /bin/cp search.php $DEPLOYPATH
    - /bin/cp sidebar.php $DEPLOYPATH
    - /bin/cp single.php $DEPLOYPATH
    - /bin/cp style-rtl.css $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH